version: 2.1

jobs:
  build:
    docker:
      - image: node:current-slim
    steps:
      - run: echo "Hello world!"
      
workflows:
  setup-workflow:
    jobs:
      - path-filtering/filter:
          base-revision: origin/develop
          config-path: .circleci/continue-config.yml
          mapping: |
            .* test-build-deploy true
