version: 2.1
setup: true

orbs:
  path-filtering: circleci/path-filtering@0.1.3

jobs:
  build:
    docker:
      - image: node:current-slim
    steps:
      - run: echo "Hello world!"
 
workflows:
  setup-workflow:
    jobs:
      - path-filtering/filter:
          base-revision: origin/main
          config-path: .circleci/continue-config.yml
          mapping: |
            .* test-build-deploy true
