parameters:
  testfile-build-deploy:
    type: boolean
    default: false

    
workflows:
  testfile-build-deploy-workflow:
    when: << pipeline.parameters.testfile-build-deploy >>
    jobs:
      - run-tests:
        context:
          - my-context
            
jobs:
  run-test:
    docker:
      - image: node:current-slim
    steps:
      - checkout
      - run:
        name: "echo test"
        command: echo TEST_ENV_VAR
            
