parameters:
  testfile-build-deploy:
    type: boolean
    default: false

    
workflows:
  testfile-build-deploy-workflow:
    when: << pipeline.parameters.testfile-build-deploy >>
    jobs:
      - run: echo "Hello world3!"
